### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by barryvdh** [jaspervdm/pogoprotos-php#5] opened 2016-07-27 11:09 UTC
As version 1.0 has now released, perhaps good to stay in sync with the upstream protos versioning and tag 1.0 here also?
https://github.com/AeonLucid/POGOProtos/releases

**Comment by jaspervdm** [comment] 2016-07-27 13:47
Yes I will do that. I tried compiling the master yesterday but it gave me a bunch of errors, but I assume v1.0 will work.

**Comment by jaspervdm** [comment] 2016-07-27 18:48
Commit `7a5ecbe` is updated to v1.0 of the proto's. It also includes a fix for #6. I will do some more testing with it and then create v1.0

**Comment by DrDelay** [comment] 2016-07-27 21:02
#6 is indeed fixed, but I still get the `Error reading byte` in line 310 mentioned in #3 . If I manually apply the changes proposed in #4 I get a new one:
`Fatal error: Uncaught Exception: new \POGOProtos\Data\PlayerData did not read the full length in /drdelay/pokemon-go/vendor/jaspervdm/pogoprotos-php/src/POGOProtos/Networking/Responses/GetPlayerResponse.proto.php:46`
I did not look into it very much until now though, it may be a mistake by me. It happens [here](https://github.com/DrDelay/pokemon-go/blob/8961b3df130e7b621bbeb0055a15b9ce6979bd2a/src/Request/AbstractApiRequest.php#L39) on a _GET_PLAYER_ Request.

Do you have a test app where both of these things don't occur?

Before releasing v1.0 this should probably be sorted out.

**Comment by jaspervdm** [comment] 2016-07-27 21:43
The PR indeed fixes the `Error reading byte`, but I wanted to test it further before merging it in. So far it seems to work well.

Concerning your other issue, `new GetPlayerResponse($resp->getReturns(0));`, where `$resp` is the `ResponseEnvelope`, works for me. Maybe the issue is the `current`? I didn't look too much in your code, but if you add more requests to the envelope the `current` might point to a different one

**Comment by DrDelay** [comment] 2016-07-31 12:54
This is a weird issue again .. if I change the condition for throwing the "did not read the full length"-Exception from `if ($len !== 0)` to `if (!empty(stream_get_contents($fp)))` it works fine and I get a _GetPlayerResponse_ with data.
Somehow _$len_ seems to not count down properly. But you say it works for you just fine? I changed nothing but what has been changed in #4 .

**Comment by jaspervdm** [comment] 2016-08-01 16:28
I did not have this specific problem so far. What specific request did you do? In any case, we might want to consider to use a different generator for our PHP code, since besides this we get many other problems as well (see also #7 ). Any opinions on this are welcome in #8

**Comment by DrDelay** [comment] 2016-08-01 16:35
This was in a `RequestType::GET_PLAYER`-Request, the response contained all the data though, and the Response-ProtobufMessage was fully populated (including the _PlayerData_) after changing the condition as I [mentioned](https://github.com/jaspervdm/pogoprotos-php/issues/5#issuecomment-236428436). 
I also tried `RequestType::GET_HATCHED_EGGS` and `RequestType::GET_PLAYER_PROFILE`, they worked fine without changing things (except #4 ).

**Comment by DrDelay** [comment] 2016-08-07 15:36
I don't think there will be any more updates for the bramp-protobufs, as it is very likely that the changes discussed in #8 get merged in. The test-protobuf branch is currently kept up to date, at AeonLucid/POGOProtos@dafa402c9b56f6ca7e388c539e6fd112d53676dd at the time of writing this (94bafb3cd34e34b9cbe3dc1ef5c003bad1ca6699). See also #15

**Closed as completed by DrDelay** 2016-08-07 15:36 UTC
